#!/usr/bin/python
# import request
import urllib2
import urllib
import json
from yamahaAvr import YamahaAVR

debug=True

host="192.168.1.121"

def printJSON(data):
    print(json.dumps(data, indent=4, sort_keys=True)) 


upstairs = YamahaAVR(host)

# radioMenuItemIndex = findMenuItemIndex(menu["max_line"],'Radio')

upstairs.resetMenu()

index = upstairs.findMenuItem('Radio')
if (index >= 0):
    if (upstairs.selectMenuItem(index)):
        print "Found Radio"
else:
    exit(1)

index = upstairs.findMenuItem('Favorites')
upstairs.selectMenuItem(index)

# index = findMenuItem('Search')
# if (index >= 0):
#     setSearchString(index,'KKJG')
# 
# index = findMenuItem('98.1 KJUG Central Coast')
# addBookmark(index)

# menu=getURL(urlPrefix+"YamahaExtendedControl/v1/netusb/getListInfo?input=net_radio&index=0&size=8&lang=en")
# menu=getURL(urlPrefix+"YamahaExtendedControl/v1/netusb/getListInfo?input=net_radio&index=8&size=8&lang=en")

upstairs.resetMenu()


# http://192.168.1.121/YamahaRemoteControl/desc.xml
# 
# 
# http://192.168.1.121/YamahaExtendedControl/v1/netusb/getPresetInfo
# http://192.168.1.121/YamahaExtendedControl/v1/system/getNameText?id=main
# http://192.168.1.121/YamahaExtendedControl/v1/system/getNetworkStatus
# http://192.168.1.121/
# http://192.168.1.141/
# 
# http://192.168.1.141/YamahaExtendedControl/v1/main/setInput?input=net_radio&mode=autoplay_disabled
# 
# http://192.168.1.141/YamahaExtendedControl/v1/system/getFeatures
# http://192.168.1.141/YamahaExtendedControl/v1/netusb/setListControl?list_id=main&type=select&index=0&zone=main
# 
# # Top Level List
# http://192.168.1.141/YamahaExtendedControl/v1/netusb/getListInfo?input=net_radio&index=0&size=8&lang=en
# 
# # Select Item
# http://192.168.1.141/YamahaExtendedControl/v1/netusb/setListControl?list_id=main&type=select&index=0&zone=main
# 
# # Add Bookmark
# http://192.168.1.141/YamahaExtendedControl/v1/netusb/manageList?list_id=main&type=add_bookmark&index=50&timeout=5000